version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

  ecoset:
    volumes:
      - ./test/cache:/cache
      - ./test/sample-data:/data
      - ./test/output:/output
      - ./test/logs:/logs
      - "./src/config/default.docker-dev.yml:/usr/src/app/config/default.yml"

  # gbifdb:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
